dic_date={
    'error_year'                      : '',
    'error_month'                     : '',
    'error_day'                       : '',
    'propose_month'                   : '',
    'propose_day'                     : '',
    'actual_month'                    : '',
    'actual_day'                      : '',
}

dic_error_information={
    'error_hour'                      : '',
    'error_minute'                    : '',
    'product_line_stop_time'          : '',
    'equipment_stop_time'             : '',
    'maintain_time'                   : '',
    'error_type1'                     : '',
    'error_type2'                     : '',
    'affect'                          : '',
    'duty'                            : '',
    'product_line'                    : '',
    'equipment_name'                  : '',
    'error_appearance'                : '',
    'error_reason'                    : '',
    'plan'                            : '',
    'error_position'                  : '',
    'error_component'                 : '',
    'deterioration_appearance'        : '',
    'main_factor'                     : '',
    # 'maintain_duration'               : '',
    'maintain_type'                   : '',
    'confirm_man'                     : '',
'note'                                : ''
}

dic_position={
    'error_year'                      : 3,
    'error_month'                     : 4,
    'error_day'                       : 5,
    'error_hour'                      : 6,
    'error_minute'                    : 7,
    'product_line_stop_time'          : 8,
    'equipment_stop_time'             : 9,
    'maintain_time'                   : 10,
    'error_type1'                     : 11,
    'error_type2'                     : 12,
    'affect'                          : 13,
    'duty'                            : 14,
    'product_line'                    : 15,
    'equipment_name'                  : 16,
    'error_appearance'                : 17,
    'error_reason'                    : 18,
    'plan'                            : 19,
    'error_position'                  : 20,
    'error_component'                 : 21,
    'deterioration_appearance'        : 22,
    'main_factor'                     : 23,
    # 'maintain_duration'               : 24,
    'propose_year'                    : 25,
    'propose_month'                   : 26,
    'propose_day'                     : 27,
    'actual_year'                     : 28,
    'actual_month'                    : 29,
    'actual_day'                      : 30,
    'maintain_type'                   : 31,
    'confirm_man'                     : 32,
    'note'                        : 33
}

dic_caption={
    'error_year'                      : '年',
    'error_month'                     : '月',
    'error_day'                       : '日',
    'error_hour'                      : '时',
    'error_minute'                    : '分',
    'product_line_stop_time'          : '生产停',
    'equipment_stop_time'             : '设备停',
    'maintain_time'                   : '修理时',
    'error_type1'                     : '新再区分',
    'error_type2'                     : '机械电气区分',
    'affect'                          : '生产影响',
    'duty'                            : '责任区分',
    'product_line'                    : '生产线',
    'equipment_name'                  : '设备名称',
    'error_appearance'                : '故障现象',
    'error_reason'                    : '故障原因',
    'plan'                            : '实施对策',
    'error_position'                  : '故障部位',
    'error_component'                 : '故障部品',
    'deterioration_appearance'        : '劣化现象',
    'main_factor'                     : '设备管理要因',
    # 'maintain_duration'               : '工数(MH)',
    'propose_year'                    : '计划年',
    'propose_month'                   : '计划月',
    'propose_day'                     : '计划日',
    'actual_year'                     : '实际年',
    'actual_month'                    : '实际月',
    'actual_day'                      : '实际日',
    'maintain_type'                   : '保全区分',
    'confirm_man'                     : '对策确认',
    'note'                            : '备注说明'
}

dic_value={
    'error_year'                      : '',
    'error_month'                     : '',
    'error_day'                       : '',
    'error_hour'                      : '',
    'error_minute'                    : '',
    'product_line_stop_time'          : '',
    'equipment_stop_time'             : '',
    'maintain_time'                   : '',
    'error_type1'                     : '',
    'error_type2'                     : '',
    'affect'                          : '',
    'duty'                            : '',
    'product_line'                    : '',
    'equipment_name'                  : '',
    'error_appearance'                : '',
    'error_reason'                    : '',
    'plan'                            : '',
    'error_position'                  : '',
    'error_component'                 : '',
    'deterioration_appearance'        : '',
    'main_factor'                     : '',
    # 'maintain_duration'               : '',
    'propose_year'                    : '',
    'propose_month'                   : '',
    'propose_day'                     : '',
    'actual_year'                     : '',
    'actual_month'                    : '',
    'actual_day'                      : '',
    'maintain_type'                   : '',
    'confirm_man'                     : '',
    'note'                                : ''
}
